name: dotnet package

on:
  push:
    branches: 
    - main
    - stage
  pull_request:
    branches: 
    - main
    - stage

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: |
        nuget sources add -name "private-packages" -Source https://nuget.telerik.com/nuget -StorePasswordInClearText -Username vitvor01@gmail.com -Password Nina1968
        dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore