# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testsystemclient

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_a82702cbe10c4dc6801ae0c568763aa6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_917b4e6ea0bc4a8da4c913316759f0aa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_a82702cbe10c4dc6801ae0c568763aa6 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testsystemclient'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eac50ae64baa4395933d17f25b4282ca }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_a82702cbe10c4dc6801ae0c568763aa6 }}/appsvc/staticsite:${{ github.sha }}'